language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4.0'
sudo: false
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g bower
  - bower install
after_script:
  - codeclimate < coverage/**/lcov.info
